name: ryu-cho

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  ryu-cho:
    name: Ryu Cho
    runs-on: ubuntu-latest
    steps:
      - uses: vuejs-translations/ryu-cho@0a768f926097fce17a38358243c50003721627fb # v1
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          username: kiaking
          email: "kia.king.08@gmail.com"
          upstream-repo: https://github.com/vitejs/docs-ja.git
          upstream-repo-branch: main
          head-repo: https://github.com/vitejs/vite
          head-repo-branch: main
          track-from: b413bcee941b2436205397a67729c9475b0e32f8
          path-starts-with: docs/
          workflow-name: ryu-cho
